# Generated by Django 4.1.6 on 2023-03-11 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_head', models.CharField(blank=True, default=None, max_length=100, verbose_name='Заголовок')),
                ('article_body', models.TextField(blank=True, default=None, max_length=1000, verbose_name='Содержимое')),
                ('date_create', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_last_change', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Изображение')),
                ('num_of_views', models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_article_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_article_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Статья в блоке',
                'verbose_name_plural': 'Статьи в блоге',
            },
        ),
    ]
