# Generated by Django 4.1.7 on 2023-03-19 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
                ('name', models.CharField(default=None, max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(default='Type here', verbose_name='Комментарий')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of', models.CharField(default=None, max_length=150, verbose_name='Наименование рассылки')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('posting_date', models.DateField(default='2023-12-29', verbose_name='Когда')),
                ('posting_time', models.TimeField(default='00:01', verbose_name='Во сколько')),
                ('frequency', models.CharField(choices=[('once a day', 'раз в день'), ('once a week', 'раз в неделю'), ('once a month', 'раз в месяц')], default='once a day', max_length=20)),
                ('mailing_status', models.CharField(choices=[('completed,', 'завершена'), ('created', 'создана'), ('launched', 'запущена'), ('disabled', 'выключена')], default='created', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('client', models.ManyToManyField(to='app_spammy.client', verbose_name='Адресат')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MessageToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of', models.CharField(default=None, max_length=150, verbose_name='Наименование письма')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('letter_subject', models.CharField(blank=True, default=None, max_length=100, verbose_name='Тема письма')),
                ('body_of_the_letter', models.TextField(blank=True, default=None, max_length=1000, verbose_name='Тело письма')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messagetosend_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('newsletter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_spammy.newsletter', verbose_name='Рассылка')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messagetosend_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщение для рассылок',
            },
        ),
    ]
