# Generated by Django 4.1.6 on 2023-03-14 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_spammy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of', models.CharField(default=None, max_length=150, verbose_name='Наименование рассылки')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('posting_date', models.DateField(default='2023-12-29', verbose_name='Когда')),
                ('posting_time', models.TimeField(default='00:01', verbose_name='Во сколько')),
                ('frequency', models.CharField(choices=[('once a day', 'раз в день'), ('once a week', 'раз в неделю'), ('once a month', 'раз в месяц')], default='once a day', max_length=20)),
                ('mailing_status', models.CharField(choices=[('completed,', 'завершена'), ('created', 'создана'), ('launched', 'запущена')], default='created', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('client', models.ManyToManyField(to='app_spammy.client', verbose_name='Адресат')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
