# Generated by Django 4.1.6 on 2023-03-15 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_spammy', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of', models.CharField(default=None, max_length=150, verbose_name='Наименование письма')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('letter_subject', models.CharField(blank=True, default=None, max_length=100, verbose_name='Тема письма')),
                ('body_of_the_letter', models.TextField(blank=True, default=None, max_length=1000, verbose_name='Тело письма')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messagetosend_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('newsletter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_spammy.newsletter', verbose_name='Рассылка')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messagetosend_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщение для рассылок',
            },
        ),
    ]
